apiVersion: v2
name: quakes
description: Dataviz réactive des évènements sismiques autour des îles Fiji depuis 1964
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Earthquake_-_The_Noun_Project.svg/512px-Earthquake_-_The_Noun_Project.svg.png
type: application
version: 1.3.4
dependencies:
  - name: shiny
    version: 0.13.0
    repository: https://inseefrlab.github.io/helm-charts
