shiny:
  image:
    repository: inseefrlab/shiny-app-template
    tag: "1.0.1"
  ingress:
    enabled: true
  s3:
    enabled: true
  postgresql:
    enabled: true
    auth:
      database: "defaultdb"
    containerPorts:
      postgresql: 5432
    fullnameOverride: quakes-db
    primary:
      persistence:
        size: 2Gi
