shiny:
  image:
    repository: ""
    tag: ""
  ingress:
    enabled: true
    hostname: ""
  s3:
    configMapName: ""
    accessKeyId: ""
    endpoint: ""
    defaultRegion: ""
    secretAccessKey: ""
    sessionToken: ""
  postgresql:
    auth:
      username: ""
      password: ""
      postgresPassword: ""
      database: ""
    containerPorts:
      postgresql: 5432
    fullnameOverride: ""
    primary:
      persistence:
        size: 2Gi
