shiny:
  image:
    repository: inseefrlab/shiny-app-template
    tag: "1.0.1"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: 
      - host: chart-example.local
        paths:
        - path: /
          pathType: Prefix
  s3:
    enabled: true
    configMapName: ""
    accessKeyId: ""
    endpoint: ""
    defaultRegion: ""
    secretAccessKey: ""
    sessionToken: ""
  postgresql:
    enabled: true
    auth:
      username: myusername
      password: changeme
      database: defaultdb
    containerPorts:
      postgresql: 5432
    fullnameOverride: quakes-db
    primary:
      persistence:
        size: 2Gi
