shiny:
  image:
    repository: "inseefrlab/shiny-app-template"
    tag: "1.0.1"
  ingress:
    enabled: true
    hostname: ""
  s3:
    enabled: true
    configMapName: ""
    accessKeyId: ""
    endpoint: ""
    defaultRegion: ""
    secretAccessKey: ""
    sessionToken: ""
  postgresql:
    enabled: true
    auth:
      username: ""
      password: ""
      postgresPassword: ""
      database: ""
    containerPorts:
      postgresql: 5432
    fullnameOverride: "quakes-db"
    primary:
      persistence:
        size: 2Gi
